trigger:
- main


pool:
  vmImage: ubuntu-latest

variables:
  isMain:: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
stages:
- stage: A
  jobs:
  - job: A1
    steps:
      - script: echo Stage A!
- stage: B
  condition: and(succeded(), eq(variables.isMain, 'true'))
  jobs:
  - job: B1
    steps:
      - script: echo Stage B
        displayName: 'echo Stagename'
      - script: echo $(isMain)
  - job: B2
    steps:
      - script: python3 test.py